SELECT TOP (1000) [Respondent]
      ,[MainBranch]
      ,[Hobbyist]
      ,[OpenSourcer]
      ,[OpenSource]
      ,[Employment]
      ,[Country]
      ,[Student]
      ,[EdLevel]
      ,[UndergradMajor]
      ,[EduOther]
      ,[OrgSize]
      ,[DevType]
      ,[YearsCode]
      ,[Age1stCode]
      ,[YearsCodePro]
      ,[CareerSat]
      ,[JobSat]
      ,[MgrIdiot]
      ,[MgrMoney]
      ,[MgrWant]
      ,[JobSeek]
      ,[LastHireDate]
      ,[LastInt]
      ,[FizzBuzz]
      ,[JobFactors]
      ,[ResumeUpdate]
      ,[CurrencySymbol]
      ,[CurrencyDesc]
      ,[CompTotal]
      ,[CompFreq]
      ,[ConvertedComp]
      ,[WorkWeekHrs]
      ,[WorkPlan]
      ,[WorkChallenge]
      ,[WorkRemote]
      ,[WorkLoc]
      ,[ImpSyn]
      ,[CodeRev]
      ,[CodeRevHrs]
      ,[UnitTests]
      ,[PurchaseHow]
      ,[PurchaseWhat]
      ,[LanguageWorkedWith]
      ,[LanguageDesireNextYear]
      ,[DatabaseWorkedWith]
      ,[DatabaseDesireNextYear]
      ,[PlatformWorkedWith]
      ,[PlatformDesireNextYear]
      ,[WebFrameWorkedWith]
      ,[WebFrameDesireNextYear]
      ,[MiscTechWorkedWith]
      ,[MiscTechDesireNextYear]
      ,[DevEnviron]
      ,[OpSys]
      ,[Containers]
      ,[BlockchainOrg]
      ,[BlockchainIs]
      ,[BetterLife]
      ,[ITperson]
      ,[OffOn]
      ,[SocialMedia]
      ,[Extraversion]
      ,[ScreenName]
      ,[SOVisit1st]
      ,[SOVisitFreq]
      ,[SOVisitTo]
      ,[SOFindAnswer]
      ,[SOTimeSaved]
      ,[SOHowMuchTime]
      ,[SOAccount]
      ,[SOPartFreq]
      ,[SOJobs]
      ,[EntTeams]
      ,[SOComm]
      ,[WelcomeChange]
      ,[SONewContent]
      ,[Age]
      ,[Gender]
      ,[Trans]
      ,[Sexuality]
      ,[Ethnicity]
      ,[Dependents]
      ,[SurveyLength]
      ,[SurveyEase]
  FROM [final_project].[dbo].[Final Project]

 SELECT
    Respondent,
    Country,
    Employment,
    Student,
    EdLevel,
    UndergradMajor,
    DevType,
    YearsCode,
    YearsCodePro,
    LanguageWorkedWith,
    DatabaseWorkedWith,
    PlatformWorkedWith,
    DevEnviron,
    OpSys,
    ConvertedComp,
    WorkWeekHrs,
    WorkRemote,
    CareerSat,
    JobSat,
    Age,
    Gender
INTO SurveyClean
FROM [final_project].[dbo].[Final Project];